FROM amd64/alpine:3.18

RUN apk add --upgrade --no-cache \
        ca-certificates-bundle \
        curl \

RUN curl -o dotnet-install.sh https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh

RUN chmod +x dotnet-install.sh

RUN ./dotnet-install.sh -Version 6.0.413
RUN ./dotnet-install.sh -Version 7.0.401
RUN ./dotnet-install.sh -Version 8.0.100-rc.1.23455.8

ENV PATH="${PATH}:/root/.dotnet"
