name: Sync
on:
  push:
    branches: [ main ]
jobs:
  sync_image:
    name: Sync Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Image
      run: |
        docker pull gcr.io/google_containers/pause:3.2
        docker tag gcr.io/google_containers/pause:3.2 dcarea/google_containers_pause:3.2
        docker push dcarea/google_containers_pause:3.2

