name: Sync
on:
  push:
    branches: [ main ]
jobs:
  sync_image:
    name: Sync Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push Image
      run: |
        docker pull ghcr.io/linkerd/dev:v39-rust-musl
        docker tag ghcr.io/linkerd/dev:v39-rust-musl dcarea/linkerd_dev:v39-rust-musl
        docker push dcarea/linkerd_dev:v39-rust-musl

