name: Sync
on:
  push:
    branches: [ main ]
jobs:
  sync_image:
    name: Sync Image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}
    - name: Push Image
      run: |
        docker pull k8s.gcr.io/sig-storage/csi-attacher:v3.0.2
        docker tag k8s.gcr.io/sig-storage/csi-attacher:v3.0.2 ghcr.io/dcarea/csi-attacher:v3.0.2
        docker push ghcr.io/dcarea/csi-attacher:v3.0.2
